import { baseAssets, basePhotos, baseRsvp } from "./base";
import type { Invite } from "./types";

/** Soft rose & sage spring garden party */
export const blush: Invite = {
  slug: "blush-garden",
  name: "Blush Garden",
  tagline: "Rose & sage spring garden — lace edges, petals and arches.",
  meta: {
    title: "Sophie & Daniel — 05.16.27",
    description: "Join us for a spring afternoon among the roses.",
  },
  theme: {
    paper: "#fbf3ef",
    ink: "#7b4f4c",
    body: "#6a4a47",
    accent: "#c98b86",
    onAccent: "#ffffff",
    circle: "#f3dcd6",
    label: "#7b4f4c",
    formBg: "#fffaf7",
    formInk: "#5a3d3a",
    field: "#f6e4df",
    button: "#b0716c",
    onPhoto: "#7b4f4c",
    cardBg: "#fffaf7",
    cardInk: "#7b4f4c",
    heroBg: "#f3d3cb",
    weekendBg: "#f4e4dd",
  },
  design: {
    fonts: {
      script: "var(--font-parisienne)",
      caps: "var(--font-marcellus)",
      body: "var(--font-eb-garamond)",
      names: "var(--font-parisienne)",
      capsTracking: "0.2em",
      namesTracking: "0",
      namesScale: 1.45,
      scriptScale: 0.95,
    },
    backdrop: { kind: "scene", scene: "garden" },
    card: "lace",
    divider: "scallop",
    dateShape: "circle",
    swatchShape: "circle",
    photoFrame: "arch",
    weekendArt: "wreath",
    weekendLayout: "split",
    wordsLayout: "split",
    weekendTexture: false,
    // Grey pencil → warm rose-brown
    sketchFilter: "sepia(0.55) hue-rotate(-28deg) saturate(1.7) brightness(1.02)",
    envelopeTint: { color: "#e2a49c", filter: "brightness(1.55) contrast(0.85)" },
    sealTint: { color: "#d49a85", filter: "brightness(1.18)" },
  },
  assets: baseAssets,
  envelope: {
    heading: "Something lovely is blooming",
    cta: "Open with Love",
    monogram: ["S", "D"],
  },
  hero: {
    kicker: ["Please join us", "for the wedding of"],
    names: "Sophie & Daniel",
    date: "05.16.27",
  },
  welcome: {
    title: "Welcome",
    body: "We're inviting our dearest people to a spring afternoon among the roses. Come celebrate our *love* with garden games, golden light and far too much cake.",
    daysLabel: "Save the Weekend",
    days: [
      { day: "14", month: "may" },
      { day: "15", month: "may" },
      { day: "16", month: "may", active: true },
      { day: "17", month: "may" },
      { day: "18", month: "may" },
    ],
  },
  weekend: {
    title: "The Weekend",
    subtitle: "In Full Bloom",
    events: [
      { time: "2:00pm", title: "Garden Ceremony", place: "Rosewood Gardens", icon: "rings" },
      { time: "3:30pm", title: "Lawn Games & Lemonade", place: "The Orchard", icon: "champagne" },
      { time: "6:00pm", title: "Supper Under the Pergola", place: "The Glasshouse", icon: "champagne" },
      { time: "8:00pm", title: "First Dance", place: "The Rose Terrace", icon: "rings" },
    ],
  },
  dressCode: {
    title: "Dress Code",
    subtitle: "Garden party pastels",
    body: "Soft florals, flowing fabrics and spring pastels. Block heels or flats are kindest to the lawn.",
    note: "Sun hats welcome — parasols will be provided.",
    swatches: [
      { name: "Blush", color: "#f0c9c2" },
      { name: "Rose", color: "#c98b86" },
      { name: "Sage", color: "#b7c2a5" },
      { name: "Lavender", color: "#c9bcd8" },
      { name: "Cream", color: "#f3e7d3" },
    ],
  },
  fewWords: {
    title: "Love Notes",
    body: "Share a favourite memory, a wish, or your recipe for a happy marriage — we’ll press every note into our wedding album.",
    photos: basePhotos,
  },
  rsvp: { ...baseRsvp, thankYou: "Thank you — we’ll save you a seat in the garden." },
};
