import { baseAssets, basePhotos, baseRsvp } from "./base";
import type { Invite } from "./types";

/** Terracotta boho wedding at golden hour in the desert */
export const desert: Invite = {
  slug: "desert-sun",
  name: "Desert Sun",
  tagline: "Terracotta boho at golden hour — mesas, dunes and line art.",
  meta: {
    title: "Luna & Mateo — 09.21.27",
    description: "Meet us where the desert meets the sky.",
  },
  theme: {
    paper: "#f7ece0",
    ink: "#7a3b22",
    body: "#6b4532",
    accent: "#c0623b",
    onAccent: "#fff7ee",
    circle: "#f0d6bf",
    label: "#7a3b22",
    formBg: "#fffaf3",
    formInk: "#5b3423",
    field: "#f3e2d0",
    button: "#a94f2b",
    onPhoto: "#6e2f17",
    cardBg: "#fbf3e8",
    cardInk: "#7a3b22",
    heroBg: "#e7a77b",
    weekendBg: "#f1dcc6",
    photoTextShadow: "0 1px 12px rgb(251 232 210 / 0.6)",
  },
  design: {
    fonts: {
      script: "var(--font-playfair)",
      caps: "var(--font-josefin)",
      body: "var(--font-lora)",
      names: "var(--font-playfair)",
      capsTracking: "0.32em",
      namesTracking: "0.06em",
      namesScale: 0.92,
      scriptScale: 0.74,
      scriptItalic: true,
      bodyScale: 0.88,
    },
    backdrop: { kind: "scene", scene: "desert" },
    card: "sunset",
    divider: "dunes",
    dateShape: "arch",
    swatchShape: "arch",
    photoFrame: "polaroid",
    weekendArt: "desert",
    weekendLayout: "split",
    wordsLayout: "reverse",
    weekendTexture: true,
    // Grey pencil → terracotta line-work
    sketchFilter: "sepia(0.9) hue-rotate(-22deg) saturate(2.4) brightness(0.88)",
    envelopeTint: { color: "#c96a42", filter: "brightness(1.3)" },
    sealTint: { color: "#86331a", filter: "brightness(0.9)" },
  },
  assets: baseAssets,
  envelope: {
    heading: "Meet us where the desert meets the sky",
    cta: "Open at Sunset",
    monogram: ["L", "M"],
  },
  hero: {
    kicker: ["Under the open sky", "we will be married"],
    names: "LUNA & MATEO",
    date: "09.21.27",
  },
  welcome: {
    title: "Welcome",
    body: "Pack your sunglasses and your dancing shoes. We're getting married under the wide desert sky, and it wouldn't be the same without *you*.",
    daysLabel: "Golden Hour Weekend",
    days: [
      { day: "19", month: "sep" },
      { day: "20", month: "sep" },
      { day: "21", month: "sep", active: true },
      { day: "22", month: "sep" },
      { day: "23", month: "sep" },
    ],
  },
  weekend: {
    title: "The Weekend",
    subtitle: "Under Open Skies",
    events: [
      { time: "5:00pm", title: "Welcome Mezcal Hour", place: "The Hacienda Courtyard", icon: "champagne" },
      { time: "6:30pm", title: "Ceremony at Sunset", place: "Joshua Tree Overlook", icon: "rings" },
      { time: "8:00pm", title: "Dinner Under the Stars", place: "The Long Table", icon: "champagne" },
      { time: "10:00pm", title: "Bonfire & Dancing", place: "The Dunes", icon: "rings" },
    ],
  },
  dressCode: {
    title: "Dress Code",
    subtitle: "Desert formal",
    body: "Earthy tones, linen and light layers — evenings in the desert turn cool once the sun goes down.",
    note: "Leave the stilettos at home; the ground is sandy and wonderfully uneven.",
    swatches: [
      { name: "Terracotta", color: "#c0623b" },
      { name: "Rust", color: "#8e3b1f" },
      { name: "Sand", color: "#e3c9a6" },
      { name: "Desert Sage", color: "#9ea58a" },
      { name: "Clay", color: "#b98a73" },
    ],
  },
  fewWords: {
    title: "Leave a Note",
    body: "Tell us a story, a wish, or your best desert-road song — we’ll read every one by the fire.",
    photos: basePhotos,
  },
  rsvp: { ...baseRsvp, thankYou: "Gracias — see you at golden hour." },
};
