import { baseAssets, basePhotos, baseRsvp } from "./base";
import type { Invite } from "./types";

export const green: Invite = {
  slug: "green-wedding-invitation",
  name: "Evergreen",
  tagline: "The original Canva design — misty forest, torn paper, pencil sketches.",
  meta: {
    title: "Matilda & Roman — 04.10.27",
    description: "You've been invited! Join us in the mountains to celebrate.",
  },
  theme: {
    paper: "#f4f2f0",
    ink: "#4c4a36",
    body: "#3a422d",
    accent: "#736b4c",
    onAccent: "#ffffff",
    circle: "#d8d9c9",
    label: "#000000",
    formBg: "#f4f2f0",
    formInk: "#2f2f26",
    field: "#dfddd8",
    button: "#3a422d",
    onPhoto: "#f4f2f0",
    cardBg: "#f4f2f0",
    cardInk: "#4c4a36",
    heroBg: "#6b6c55",
    weekendBg: "#d8d9c9",
  },
  design: {
    fonts: {
      script: "var(--font-pinyon)",
      caps: "var(--font-cormorant)",
      body: "var(--font-eb-garamond)",
      names: "var(--font-cormorant)",
    },
    backdrop: { kind: "photo", src: "/invites/green/landscape.jpg" },
    card: "ticket",
    divider: "torn",
    dateShape: "circle",
    swatchShape: "circle",
    photoFrame: "polaroid",
    weekendArt: "mountain",
    weekendLayout: "split",
    wordsLayout: "split",
    weekendTexture: true,
    canvaOffsets: true,
  },
  assets: baseAssets,
  envelope: {
    heading: "You’ve been invited!",
    cta: "Press to Open",
    monogram: ["M", "R"],
  },
  hero: {
    kicker: ["With Love", "and Gateful Hearts"],
    names: "MATILDA & ROMAN",
    date: "04.10.27",
  },
  welcome: {
    title: "Welcome",
    body: "We're so excited to share this special weekend with our favorite people. Join us in the mountains to celebrate our *love*, our story, and the adventure ahead.",
    daysLabel: "The Big Day",
    days: [
      { day: "02", month: "oct" },
      { day: "03", month: "oct" },
      { day: "04", month: "oct", active: true },
      { day: "05", month: "oct" },
      { day: "06", month: "oct" },
    ],
  },
  weekend: {
    title: "The Weekend",
    subtitle: "At a Glance",
    events: [
      { time: "4:00pm", title: "Guest Arrival & Check-In", place: "Estes Park Lodge", icon: "champagne" },
      { time: "6:00pm", title: "Welcome Dinner", place: "The Pines Restaurant", icon: "champagne" },
      { time: "6:00pm", title: "Ceremony & Celebration", place: "The Pines Restaurant", icon: "rings" },
      { time: "6:00pm", title: "Ceremony & Celebration", place: "The Pines Restaurant", icon: "rings" },
    ],
  },
  dressCode: {
    title: "Dress Code",
    subtitle: "Inspired by the mountains",
    body: "We’d love to see you in soft, earthy tones inspired by our woodland setting. Choose a shade you feel wonderful in.",
    note: "Bring a light layer and shoes suitable for outdoor paths.",
    swatches: [
      { name: "Sage", color: "#a8ab93" },
      { name: "Olive", color: "#635f43" },
      { name: "Forest", color: "#374437" },
      { name: "Dusty Rose", color: "#b3938d" },
      { name: "Warm Taupe", color: "#aa9782" },
    ],
  },
  fewWords: {
    title: "A Few Words",
    body: "Your love and support mean the world to us. If you'd like to share a note, a story, or words of wisdom, we'd be so grateful.",
    photos: basePhotos,
  },
  rsvp: baseRsvp,
  story: {
    hero: { kicker: "The story of Matilda & Roman", title: "Our Story", since: "Est. 2019" },
    intro: {
      title: "How it Began",
      body: "Some love stories begin with fireworks. Ours began with a wrong turn on a mountain trail, a shared thermos of coffee, and a conversation *neither of us* wanted to end.",
    },
    journey: {
      title: "Our Journey",
      subtitle: "2019 — 2027",
      chapters: [
        {
          year: "2019",
          title: "A Wrong Turn",
          body: "Matilda was lost somewhere above Bear Lake; Roman insisted he wasn't. Together they found the trail — and, as it turns out, each other.",
          art: "mountain",
        },
        {
          year: "2020",
          title: "First Adventure",
          body: "A rainy weekend in a borrowed cabin, one deck of cards, and the quiet realisation that every adventure was better together.",
          art: "champagne",
        },
        {
          year: "2022",
          title: "Finding Home",
          body: "Two tiny apartments became one slightly bigger one, with a stubborn sourdough starter and a houseplant named Gerald.",
          art: "branch",
        },
        {
          year: "2025",
          title: "The Question",
          body: "At sunrise, on the same trail where we first met, Roman got down on one knee. Matilda said yes before he finished asking.",
          art: "rings",
        },
        {
          year: "2027",
          title: "Forever",
          body: "Now we're heading back to the mountains to promise each other forever — surrounded by the people we love most.",
          art: "seal",
        },
      ],
    },
    quote: "Of all the paths we’ve wandered, the best one led us to *each other*.",
    proposal: {
      title: "The Proposal",
      subtitle: "Sunrise at Bear Lake",
      body: "Roman had carried the ring up the mountain for three hikes in a row, waiting for the right light. On the fourth, the sun broke over the peaks, the lake turned to gold, and he finally found his words.",
      photos: basePhotos,
    },
    closing: {
      title: "To be Continued",
      body: "The next chapter begins in the mountains on October 4th, 2027 — and we’d love for you to be part of it.",
      invitationCta: "View the Invitation",
      rsvpCta: "RSVP",
    },
    linkLabel: "Read Our Story",
  },
};
