import { baseAssets, basePhotos, baseRsvp } from "./base";
import type { Invite } from "./types";

/** Navy & gold art-deco evening — New Year's Eve gala */
export const midnight: Invite = {
  slug: "midnight-gala",
  name: "Midnight Gala",
  tagline: "Navy & gold art deco under a twinkling night sky.",
  meta: {
    title: "Eleanor & James — 12.31.27",
    description: "Ring in the new year — and our forever — with us.",
  },
  theme: {
    paper: "#0f1a2e",
    ink: "#e3c88f",
    body: "#d8d3c5",
    accent: "#c9a45c",
    onAccent: "#0f1a2e",
    circle: "rgb(201 164 92 / 0.08)",
    label: "#e9dfc7",
    formBg: "#f5efe3",
    formInk: "#1b2338",
    field: "#e9e1d0",
    button: "#1d2b4a",
    onPhoto: "#f3e7cc",
    cardBg: "#14213b",
    cardInk: "#e3c88f",
    heroBg: "#0b1426",
    weekendBg: "#0a1222",
    timeline: "#c9a45c",
  },
  design: {
    fonts: {
      script: "var(--font-great-vibes)",
      caps: "var(--font-cinzel)",
      body: "var(--font-cormorant)",
      names: "var(--font-cinzel)",
      capsTracking: "0.22em",
      namesTracking: "0.12em",
      namesScale: 0.86,
      scriptScale: 1.05,
    },
    backdrop: { kind: "scene", scene: "night" },
    card: "deco",
    divider: "deco",
    dateShape: "ring",
    swatchShape: "diamond",
    photoFrame: "deco",
    weekendArt: "mountain",
    weekendLayout: "reverse",
    wordsLayout: "reverse",
    weekendTexture: false,
    // Pencil sketches → warm gold line-work on navy
    sketchFilter: "invert(1) sepia(0.7) saturate(2.2) hue-rotate(-6deg) brightness(0.92)",
    envelopeTint: { color: "#1e2d52", filter: "brightness(0.62) contrast(1.15)" },
  },
  assets: baseAssets,
  envelope: {
    heading: "An evening among the stars",
    cta: "Break the Seal",
    monogram: ["E", "J"],
  },
  hero: {
    kicker: ["Together with their families", "request your company"],
    names: "ELEANOR & JAMES",
    date: "12.31.27",
  },
  welcome: {
    title: "Welcome",
    body: "Join us as we ring in the new year — and our *forever* — with an evening of candlelight, champagne, and dancing until the stars fade.",
    daysLabel: "New Year’s Eve",
    days: [
      { day: "29", month: "dec" },
      { day: "30", month: "dec" },
      { day: "31", month: "dec", active: true },
      { day: "01", month: "jan" },
      { day: "02", month: "jan" },
    ],
  },
  weekend: {
    title: "The Evening",
    subtitle: "Order of Events",
    events: [
      { time: "6:00pm", title: "Champagne Reception", place: "The Starlight Terrace", icon: "champagne" },
      { time: "7:00pm", title: "Ceremony", place: "The Grand Ballroom", icon: "rings" },
      { time: "8:30pm", title: "Dinner & Dancing", place: "The Grand Ballroom", icon: "champagne" },
      { time: "11:59pm", title: "The Midnight Toast", place: "The Rooftop", icon: "champagne" },
    ],
  },
  dressCode: {
    title: "Dress Code",
    subtitle: "Black tie, after dark",
    body: "Think velvet, satin and a little sparkle. Gowns and tuxedos encouraged — jewel tones always welcome.",
    note: "Valet parking and a coat check will be available all evening.",
    swatches: [
      { name: "Midnight", color: "#1a2747" },
      { name: "Champagne", color: "#e8d5ae" },
      { name: "Gold", color: "#c9a45c" },
      { name: "Emerald", color: "#1f4d3f" },
      { name: "Burgundy", color: "#6b1f2e" },
    ],
  },
  fewWords: {
    title: "A Few Words",
    body: "Before the clock strikes twelve, leave us a wish for the year ahead — a memory, a toast, or a little advice for the road.",
    photos: basePhotos,
  },
  rsvp: { ...baseRsvp, thankYou: "Thank you — see you at midnight." },
};
